alias ls='ls --color=auto'
alias l='ls -la'
alias ld='ls -lDa'
alias grep='grep --color=auto'
alias update='sudo pacman -Syu'
alias add='sudo pacman -S'
alias remove='sudo pacman -Rns'
alias search='sudo pacman -Ss'
alias programs='sudo pacman -Qe'
alias c='clear'
alias gc='git commit'
alias ga='git add'
alias mount='mount |column -t'
alias nf='neofetch'
alias audio='pulsemixer'
alias jobs='crontab -l'
alias editjobs='crontab -e'
alias wp='~/Scripts/setRandomWallpaper.sh'
alias prop='xprop'
alias mirror='xrandr --output DP-2 --mode 1920x1080 --rate 240 --left-of HDMI-0'
alias smci='sudo make clean install'
alias nnn='nnn -e'
alias suspend='systemctl suspend'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'
